// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mltjnmgxntutablirqus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sdGpubWd4bnR1dGFibGlycXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTU2NTYsImV4cCI6MjA2NzM3MTY1Nn0.Y0wbueg_HNwcZrWP6BvhJ0JIrZmzyTgQeDSlRFGKh6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});